1.Import libraries

In [1]:
import numpy as np
import pandas as pd

2.Load the CSV file

In [2]:
df=pd.read_csv("HAM10000_metadata.csv")

In [3]:
df.head()

     lesion_id      image_id   dx dx_type   age   sex localization
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear

In [4]:
df.tail()

         lesion_id      image_id     dx dx_type   age     sex localization
10010  HAM_0002867  ISIC_0033084  akiec   histo  40.0    male      abdomen
10011  HAM_0002867  ISIC_0033550  akiec   histo  40.0    male      abdomen
10012  HAM_0002867  ISIC_0033536  akiec   histo  40.0    male      abdomen
10013  HAM_0000239  ISIC_0032854  akiec   histo  80.0    male         face
10014  HAM_0003521  ISIC_0032258    mel   histo  70.0  female         back

3.Understand the dataset

In [5]:
df.shape

(10015, 7)

In [6]:
df.columns  #Column names

Index(['lesion_id', 'image_id', 'dx', 'dx_type', 'age', 'sex', 'localization'], dtype='str')

In [7]:
df.dtypes #datatypes

lesion_id           str
image_id            str
dx                  str
dx_type             str
age             float64
sex                 str
localization        str
dtype: object

In [8]:
#Dataset Information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10015 entries, 0 to 10014
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lesion_id     10015 non-null  str
 1   image_id      10015 non-null  str
 2   dx            10015 non-null  str
 3   dx_type       10015 non-null  str
 4   age           9958 non-null   float64
 5   sex           10015 non-null  str
 6   localization  10015 non-null  str
dtypes: float64(1), str(6)
memory usage: 547.8 KB

In [9]:
#statistical summary
df.describe()

               age
count  9958.000000
mean     51.863828
std      16.968614
min       0.000000
25%      40.000000
50%      50.000000
75%      65.000000
max      85.000000

4.Check missing values

In [10]:
df.isnull().sum()

lesion_id        0
image_id         0
dx               0
dx_type          0
age             57
sex              0
localization     0
dtype: int64

In [11]:
#percentage of missing values
(df.isnull().sum())/len(df)*100

lesion_id       0.000000
image_id        0.000000
dx              0.000000
dx_type         0.000000
age             0.569146
sex             0.000000
localization    0.000000
dtype: float64

In [12]:
#find rows containing missing values
df[df.isnull().any(axis=1)]

        lesion_id      image_id   dx    dx_type  age      sex     localization
968   HAM_0001186  ISIC_0033391  bkl  consensus  NaN  unknown          unknown
969   HAM_0002660  ISIC_0033750  bkl  consensus  NaN  unknown          unknown
970   HAM_0000372  ISIC_0033685  bkl  consensus  NaN  unknown          unknown
971   HAM_0000948  ISIC_0033631  bkl  consensus  NaN  unknown          unknown
972   HAM_0000983  ISIC_0033490  bkl  consensus  NaN  unknown          unknown
973   HAM_0007281  ISIC_0034283  bkl  consensus  NaN  unknown          unknown
974   HAM_0001561  ISIC_0032740  bkl  consensus  NaN  unknown          unknown
975   HAM_0000825  ISIC_0034186  bkl  consensus  NaN  unknown          unknown
977   HAM_0006074  ISIC_0034252  bkl  consensus  NaN  unknown          unknown
978   HAM_0006074  ISIC_0033829  bkl  consensus  NaN  unknown          unknown
1886  HAM_0000169  ISIC_0032960  mel      histo  NaN     male             face
1887  HAM_0000169  ISIC_0033708  mel      histo  NaN     male             face
7558  HAM_0007278  ISIC_0025009   nv      histo  NaN   female            chest
7961  HAM_0002417  ISIC_0033442   nv      histo  NaN     male  upper extremity
7962  HAM_0002417  ISIC_0032943   nv      histo  NaN     male  upper extremity
8410  HAM_0006706  ISIC_0031725   nv      histo  NaN   female          abdomen
8411  HAM_0004924  ISIC_0027040   nv      histo  NaN   female            trunk
8555  HAM_0007278  ISIC_0032300   nv      histo  NaN   female            chest
9386  HAM_0000698  ISIC_0031668   nv  consensus  NaN     male             foot
9387  HAM_0000698  ISIC_0027431   nv  consensus  NaN     male             foot
9593  HAM_0006766  ISIC_0033374   nv  consensus  NaN  unknown          unknown
9594  HAM_0004237  ISIC_0033877   nv  consensus  NaN  unknown          unknown
9595  HAM_0007460  ISIC_0032578   nv  consensus  NaN  unknown          unknown
9596  HAM_0000822  ISIC_0033841   nv  consensus  NaN  unknown          unknown
9597  HAM_0006644  ISIC_0033882   nv  consensus  NaN  unknown          unknown
9598  HAM_0004120  ISIC_0034266   nv  consensus  NaN  unknown          unknown
9599  HAM_0005257  ISIC_0033751   nv  consensus  NaN  unknown          unknown
9600  HAM_0001619  ISIC_0033065   nv  consensus  NaN  unknown          unknown
9601  HAM_0001147  ISIC_0033375   nv  consensus  NaN  unknown          unknown
9602  HAM_0004508  ISIC_0033628   nv  consensus  NaN  unknown          unknown
9603  HAM_0002037  ISIC_0033733   nv  consensus  NaN  unknown          unknown
9604  HAM_0007191  ISIC_0032738   nv  consensus  NaN  unknown          unknown
9605  HAM_0001000  ISIC_0033353   nv  consensus  NaN  unknown          unknown
9606  HAM_0000627  ISIC_0034019   nv  consensus  NaN  unknown          unknown
9607  HAM_0002164  ISIC_0032852   nv  consensus  NaN  unknown          unknown
9608  HAM_0000421  ISIC_0034080   nv  consensus  NaN  unknown          unknown
9609  HAM_0003561  ISIC_0034154   nv  consensus  NaN  unknown          unknown
9610  HAM_0004430  ISIC_0032789   nv  consensus  NaN  unknown          unknown
9611  HAM_0007301  ISIC_0033417   nv  consensus  NaN  unknown          unknown
9612  HAM_0003935  ISIC_0033782   nv  consensus  NaN  unknown          unknown
9613  HAM_0001118  ISIC_0033332   nv  consensus  NaN  unknown          unknown
9614  HAM_0007172  ISIC_0034130   nv  consensus  NaN  unknown          unknown
9615  HAM_0003696  ISIC_0032945   nv  consensus  NaN  unknown          unknown
9616  HAM_0005439  ISIC_0033597   nv  consensus  NaN  unknown          unknown
9617  HAM_0002282  ISIC_0034045   nv  consensus  NaN  unknown          unknown
9618  HAM_0001139  ISIC_0033028   nv  consensus  NaN  unknown          unknown
9619  HAM_0003998  ISIC_0033809   nv  consensus  NaN  unknown          unknown
9620  HAM_0003034  ISIC_0033187   nv  consensus  NaN  unknown          unknown
9621  HAM_0001366  ISIC_0032814   nv  consensus  NaN  unknown          unknown
9622  HAM_0004670  ISIC_0033190   nv  consensus  NaN  unknown          unknown
9623  HAM_0003017  ISIC_0033535   nv  consensus  NaN  unknown          unknown
9624  HAM_0005156  ISIC_0033330   nv  consensus  NaN  unknown          unknown
9625  HAM_0001209  ISIC_0033064   nv  consensus  NaN  unknown          unknown
9626  HAM_0002402  ISIC_0033515   nv  consensus  NaN  unknown          unknown
9627  HAM_0001433  ISIC_0033735   nv  consensus  NaN  unknown          unknown
9628  HAM_0006643  ISIC_0033982   nv  consensus  NaN  unknown          unknown
9629  HAM_0003300  ISIC_0034195   nv  consensus  NaN  unknown          unknown

5.Handle missing values

In [13]:
df["age"]=df["age"].fillna(df["age"].median())

In [14]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [lesion_id, image_id, dx, dx_type, age, sex, localization]
Index: []

In [15]:
df[df["age"]==df["age"].median()]

        lesion_id      image_id     dx dx_type   age     sex     localization
43    HAM_0007409  ISIC_0025076    bkl   histo  50.0    male  upper extremity
44    HAM_0007409  ISIC_0029687    bkl   histo  50.0    male  upper extremity
45    HAM_0007409  ISIC_0025642    bkl   histo  50.0    male  upper extremity
59    HAM_0000728  ISIC_0025286    bkl   histo  50.0    male  lower extremity
107   HAM_0001665  ISIC_0027957    bkl   histo  50.0    male  lower extremity
...           ...           ...    ...     ...   ...     ...              ...
9942  HAM_0007088  ISIC_0024800  akiec   histo  50.0    male             back
9961  HAM_0001023  ISIC_0026468  akiec   histo  50.0    male             hand
9964  HAM_0001903  ISIC_0026984  akiec   histo  50.0    male             face
9965  HAM_0001302  ISIC_0032206  akiec   histo  50.0    male             neck
9988  HAM_0001036  ISIC_0027588  akiec   histo  50.0  female             face

[1244 rows x 7 columns]

In [16]:
df["sex"]=df["sex"].fillna(df["sex"].mode()[0])

In [17]:
df["localization"]=df["localization"].fillna(df["localization"].mode()[0])

6.Check duplicate records

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.shape

(10015, 7)

7.select one column

In [20]:
df["age"]

0        80.0
1        80.0
2        80.0
3        80.0
4        75.0
         ...
10010    40.0
10011    40.0
10012    40.0
10013    80.0
10014    70.0
Name: age, Length: 10015, dtype: float64

In [21]:
#select multiple columns
df[["age","sex","dx"]]

        age     sex     dx
0      80.0    male    bkl
1      80.0    male    bkl
2      80.0    male    bkl
3      80.0    male    bkl
4      75.0    male    bkl
...     ...     ...    ...
10010  40.0    male  akiec
10011  40.0    male  akiec
10012  40.0    male  akiec
10013  80.0    male  akiec
10014  70.0  female    mel

[10015 rows x 3 columns]

In [22]:
#select first 10 rows
df.head(10)

     lesion_id      image_id   dx dx_type   age     sex localization
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0    male        scalp
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0    male        scalp
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0    male        scalp
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0    male        scalp
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0    male          ear
5  HAM_0001466  ISIC_0027850  bkl   histo  75.0    male          ear
6  HAM_0002761  ISIC_0029176  bkl   histo  60.0    male         face
7  HAM_0002761  ISIC_0029068  bkl   histo  60.0    male         face
8  HAM_0005132  ISIC_0025837  bkl   histo  70.0  female         back
9  HAM_0005132  ISIC_0025209  bkl   histo  70.0  female         back

8.Numpy operation on age

In [23]:
age=df["age"].to_numpy()

In [24]:
#mean
np.mean(age)

np.float64(51.853220169745384)

In [25]:
result={
"median":np.median(age),  #median
"minimum":np.min(age),     #min
"maximum":np.max(age),  #maximum
"std":np.std(age),  #standard
"variance":np.var(age)  #varianve
}
print(result)

{'median': np.float64(50.0), 'minimum': np.float64(0.0), 'maximum': np.float64(85.0), 'std': np.float64(16.919988013393876), 'variance': np.float64(286.28599437339244)}

9.skin cancer diagnosis analysis
the dx column contain the diagnosis analysis

In [26]:
df["dx"].unique()

<StringArray>
['bkl', 'nv', 'df', 'mel', 'vasc', 'bcc', 'akiec']
Length: 7, dtype: str

In [27]:
#using numpy 
np.unique(df["dx"])

array(['akiec', 'bcc', 'bkl', 'df', 'mel', 'nv', 'vasc'], dtype=object)

In [28]:
#count each diagnosis
df["dx"].value_counts()

dx
nv       6705
mel      1113
bkl      1099
bcc       514
akiec     327
vasc      142
df        115
Name: count, dtype: int64

10.check gender distribution

In [29]:
df["sex"].value_counts()

sex
male       5406
female     4552
unknown      57
Name: count, dtype: int64

In [30]:
#using numpy
np.unique(df["sex"],return_counts=True)

(array(['female', 'male', 'unknown'], dtype=object), array([4552, 5406,   57]))

11.check body location distribution

In [31]:
df["localization"].value_counts()

localization
back               2192
lower extremity    2077
trunk              1404
upper extremity    1118
abdomen            1022
face                745
chest               407
foot                319
unknown             234
neck                168
scalp               128
hand                 90
ear                  56
genital              48
acral                 7
Name: count, dtype: int64

12.filter data

In [32]:
#patients older than 50
df[df["age"]>50]

         lesion_id      image_id     dx dx_type   age     sex     localization
0      HAM_0000118  ISIC_0027419    bkl   histo  80.0    male            scalp
1      HAM_0000118  ISIC_0025030    bkl   histo  80.0    male            scalp
2      HAM_0002730  ISIC_0026769    bkl   histo  80.0    male            scalp
3      HAM_0002730  ISIC_0025661    bkl   histo  80.0    male            scalp
4      HAM_0001466  ISIC_0031633    bkl   histo  75.0    male              ear
...            ...           ...    ...     ...   ...     ...              ...
10007  HAM_0001565  ISIC_0028619  akiec   histo  60.0  female             face
10008  HAM_0001576  ISIC_0033705  akiec   histo  60.0    male             face
10009  HAM_0005705  ISIC_0031430  akiec   histo  75.0  female  lower extremity
10013  HAM_0000239  ISIC_0032854  akiec   histo  80.0    male             face
10014  HAM_0003521  ISIC_0032258    mel   histo  70.0  female             back

[4611 rows x 7 columns]

In [33]:
#patients younger than 30
df[df["age"]<30]

        lesion_id      image_id   dx    dx_type   age     sex     localization
117   HAM_0007179  ISIC_0025906  bkl      histo   0.0  female             back
118   HAM_0007179  ISIC_0027151  bkl      histo   0.0  female             back
865   HAM_0006186  ISIC_0029320  bkl  consensus   0.0    male  lower extremity
866   HAM_0006186  ISIC_0029427  bkl  consensus   0.0    male  lower extremity
902   HAM_0004543  ISIC_0032170  bkl  consensus   0.0  female             back
...           ...           ...  ...        ...   ...     ...              ...
9680  HAM_0001410  ISIC_0024830   nv  consensus  15.0  female            chest
9681  HAM_0003965  ISIC_0028380   nv  consensus  15.0  female             back
9682  HAM_0006283  ISIC_0027924   nv  consensus  20.0    male            chest
9683  HAM_0000102  ISIC_0031547   nv  consensus  20.0    male             back
9684  HAM_0000102  ISIC_0032221   nv  consensus  20.0    male             back

[659 rows x 7 columns]

In [34]:
#melanoma records
mel=df[df["dx"]=="mel"]
mel.head()

        lesion_id      image_id   dx dx_type   age     sex     localization
1211  HAM_0000871  ISIC_0025964  mel   histo  40.0  female            chest
1212  HAM_0000871  ISIC_0030623  mel   histo  40.0  female            chest
1213  HAM_0000040  ISIC_0027190  mel   histo  80.0    male  upper extremity
1214  HAM_0005678  ISIC_0031023  mel   histo  60.0    male            chest
1215  HAM_0005678  ISIC_0028086  mel   histo  60.0    male            chest

In [35]:
#basal cell carcinoma
bcc=df[df["dx"]=="bcc"]
bcc.head()

        lesion_id      image_id   dx dx_type   age     sex localization
2462  HAM_0000781  ISIC_0028155  bcc   histo  50.0    male         back
2463  HAM_0003220  ISIC_0034093  bcc   histo  80.0  female         face
2464  HAM_0007141  ISIC_0029230  bcc   histo  50.0    male        trunk
2465  HAM_0007141  ISIC_0031513  bcc   histo  50.0    male        trunk
2466  HAM_0007009  ISIC_0032384  bcc   histo  50.0    male         back

M13.multiple condition

In [36]:
df[(df["dx"]=="mel")&(df["age"]>50)]

         lesion_id      image_id   dx dx_type   age     sex     localization
1213   HAM_0000040  ISIC_0027190  mel   histo  80.0    male  upper extremity
1214   HAM_0005678  ISIC_0031023  mel   histo  60.0    male            chest
1215   HAM_0005678  ISIC_0028086  mel   histo  60.0    male            chest
1218   HAM_0007310  ISIC_0026120  mel   histo  55.0    male             back
1219   HAM_0007310  ISIC_0028412  mel   histo  55.0    male             back
...            ...           ...  ...     ...   ...     ...              ...
2314   HAM_0004047  ISIC_0030277  mel   histo  55.0  female  upper extremity
2315   HAM_0003171  ISIC_0025941  mel   histo  55.0    male             back
2316   HAM_0003509  ISIC_0027832  mel   histo  75.0    male  lower extremity
2319   HAM_0001953  ISIC_0025611  mel   histo  65.0    male             back
10014  HAM_0003521  ISIC_0032258  mel   histo  70.0  female             back

[799 rows x 7 columns]

14.sorting

In [37]:
#by age
df.sort_values("age")

,lesion_id,image_id,dx,dx_type,age,sex,localization
7500,HAM_0004176,ISIC_0033373,nv,histo,0.0,male,upper extremity
2398,HAM_0004542,ISIC_0024402,vasc,consensus,0.0,female,back
2399,HAM_0004542,ISIC_0027256,vasc,consensus,0.0,female,back
2389,HAM_0002610,ISIC_0030606,vasc,consensus,0.0,female,abdomen
2388,HAM_0002610,ISIC_0026876,vasc,consensus,0.0,female,abdomen
...,...,...,...,...,...,...,...
35,HAM_0000351,ISIC_0024324,bkl,histo,85.0,male,back
7270,HAM_0000380,ISIC_0025836,nv,histo,85.0,female,back
1224,HAM_0006722,ISIC_0031499,mel,histo,85.0,female,lower extremity
1223,HAM_0006722,ISIC_0030443,mel,histo,85.0,female,lower extremity
7269,HAM_0000380,ISIC_0024344,nv,histo,85.0,female,back

15.group by

In [38]:
df.groupby("dx")["age"].mean()

dx
akiec    66.529052
bcc      66.828794
bkl      64.153776
df       53.043478
mel      60.660377
nv       46.501119
vasc     51.373239
Name: age, dtype: float64

In [39]:
df.groupby("dx").size()

dx
akiec     327
bcc       514
bkl      1099
df        115
mel      1113
nv       6705
vasc      142
dtype: int64